FROM postgres:13-alpine

# Create the user 'postgres' with UID 999
# RUN addgroup -g 999 postgres && adduser -D -u 999 -G postgres postgres

# Fix ownership of the data and run directories
RUN chown -R postgres:postgres /var/lib/postgresql/data /var/run/postgresql

USER postgres

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["postgres"]
