apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: stox
  name: order-service-role
rules:
- apiGroups: [""] # Core API group
  resources: ["pods", "pods/log", "services", "endpoints", "configmaps", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"] # For Deployments
  resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
  verbs: ["get", "list", "watch"]